// permissions/config.js
export const PERMISSIONS = {
  DASHBOARD: 'dashboard',

  // User Management
  USER_VIEW: 'user:view',
  USER_CREATE: 'user:create',
  USER_EDIT: 'user:edit',
  USER_DELETE: 'user:delete',
  USER_DEV: 'user:dev',

  //production
  PRODUCTION_VIEW: 'production:view',
  PRODUCTION_CREATE: 'production:create',
  PRODUCTION_EDIT: 'production:edit',

  // Mold Design
  MOLD_VIEW: 'mold:view',
  MOLD_CREATE: 'mold:create',
  MOLD_EDIT: 'mold:edit',

  //stock gem
  STOCK_GEM_VIEW: 'stock-gem:view',
  STOCK_GEM_CREATE: 'stock-gem:create',
  STOCK_GEM_EDIT: 'stock-gem:edit',

  //stock product
  STOCK_PRODUCT: 'stock-product:view',
  STOCK_PRODUCT_GR_PRODUCTION: 'stock-product-gr:view',
  STOCK_PRODUCT_GR_PRODUCTION_CREATE: 'stock-product-gr:create',
  STOCK_PRODUCT_GR_IMAGE_CREATE: 'stock-product-gr-image:create',

  //customer
  CUSTOMER_VIEW: 'customer:view',
  CUSTOMER_CREATE: 'customer:create',
  CUSTOMER_EDIT: 'customer:edit',

  //worker
  WORKER_VIEW: 'worker:view',
  WORKER_CREATE: 'worker:create',
  WORKER_EDIT: 'worker:edit',

  //report
  REPORT_VIEW: 'report:view',

  //master
  MASTER_VIEW: 'master:view',

  //sale
  SALE_VIEW: 'sale:view',
  SALE_CREATE: 'sale:create',

  // ========== Mobile-Specific Features ==========
  // Mobile Dashboard (ทุกคนเข้าได้)
  MOBILE_DASHBOARD: 'mobile:dashboard',

  // Mobile Scan QR (สำหรับ stock, production tracking)
  MOBILE_SCAN: 'mobile:scan',

  // Mobile Tasks (งานของฉัน - สำหรับพนักงานผลิต)
  MOBILE_TASKS: 'mobile:tasks',

  // Mobile Profile (ทุกคนเข้าได้)
  MOBILE_PROFILE: 'mobile:profile',

  // Mobile Notifications
  MOBILE_NOTIFICATIONS: 'mobile:notifications'
}

// Role Permission Mapping
export const ROLE_PERMISSIONS = {
  Dev: [
    PERMISSIONS.DASHBOARD,

    PERMISSIONS.USER_VIEW,
    PERMISSIONS.USER_CREATE,
    PERMISSIONS.USER_EDIT,
    PERMISSIONS.USER_DELETE,
    PERMISSIONS.USER_DEV,

    PERMISSIONS.PRODUCTION_VIEW,
    PERMISSIONS.PRODUCTION_CREATE,
    PERMISSIONS.PRODUCTION_EDIT,

    PERMISSIONS.MOLD_VIEW,
    PERMISSIONS.MOLD_CREATE,
    PERMISSIONS.MOLD_EDIT,

    PERMISSIONS.STOCK_GEM_VIEW,
    PERMISSIONS.STOCK_GEM_CREATE,
    PERMISSIONS.STOCK_GEM_EDIT,

    PERMISSIONS.STOCK_PRODUCT,
    PERMISSIONS.STOCK_PRODUCT_GR_PRODUCTION,
    PERMISSIONS.STOCK_PRODUCT_GR_PRODUCTION_CREATE,
    PERMISSIONS.STOCK_PRODUCT_GR_IMAGE_CREATE,

    PERMISSIONS.CUSTOMER_VIEW,
    PERMISSIONS.CUSTOMER_CREATE,
    PERMISSIONS.CUSTOMER_EDIT,

    PERMISSIONS.WORKER_VIEW,
    PERMISSIONS.WORKER_CREATE,
    PERMISSIONS.WORKER_EDIT,

    PERMISSIONS.REPORT_VIEW,

    PERMISSIONS.MASTER_VIEW,

    PERMISSIONS.SALE_VIEW,
    PERMISSIONS.SALE_CREATE,

    // Mobile Features (Dev มีสิทธิ์ทั้งหมด)
    PERMISSIONS.MOBILE_DASHBOARD,
    PERMISSIONS.MOBILE_SCAN,
    PERMISSIONS.MOBILE_TASKS,
    PERMISSIONS.MOBILE_PROFILE,
    PERMISSIONS.MOBILE_NOTIFICATIONS
  ],

  Admin: [
    PERMISSIONS.DASHBOARD,

    PERMISSIONS.USER_VIEW,
    PERMISSIONS.USER_CREATE,
    PERMISSIONS.USER_EDIT,

    PERMISSIONS.PRODUCTION_VIEW,
    PERMISSIONS.PRODUCTION_CREATE,
    PERMISSIONS.PRODUCTION_EDIT,

    PERMISSIONS.MOLD_VIEW,
    PERMISSIONS.MOLD_CREATE,
    PERMISSIONS.MOLD_EDIT,

    PERMISSIONS.STOCK_GEM_VIEW,
    PERMISSIONS.STOCK_GEM_CREATE,
    PERMISSIONS.STOCK_GEM_EDIT,

    PERMISSIONS.CUSTOMER_VIEW,
    PERMISSIONS.CUSTOMER_CREATE,
    PERMISSIONS.CUSTOMER_EDIT,

    PERMISSIONS.WORKER_VIEW,
    PERMISSIONS.WORKER_CREATE,
    PERMISSIONS.WORKER_EDIT,

    PERMISSIONS.REPORT_VIEW,

    PERMISSIONS.MASTER_VIEW,

    // Mobile Features (Admin มีสิทธิ์ทั้งหมด)
    PERMISSIONS.MOBILE_DASHBOARD,
    PERMISSIONS.MOBILE_SCAN,
    PERMISSIONS.MOBILE_TASKS,
    PERMISSIONS.MOBILE_PROFILE,
    PERMISSIONS.MOBILE_NOTIFICATIONS
  ],

  StockOperator: [
    PERMISSIONS.STOCK_PRODUCT,
    PERMISSIONS.STOCK_PRODUCT_GR_PRODUCTION,
    PERMISSIONS.STOCK_PRODUCT_GR_PRODUCTION_CREATE,
    PERMISSIONS.STOCK_PRODUCT_GR_IMAGE_CREATE,

    // Mobile Features (เฉพาะ stock-related)
    PERMISSIONS.MOBILE_DASHBOARD,
    PERMISSIONS.MOBILE_SCAN, // สแกน QR สต็อก
    PERMISSIONS.MOBILE_PROFILE
  ],

  ProductionOperator: [
    PERMISSIONS.PRODUCTION_VIEW,
    PERMISSIONS.PRODUCTION_CREATE,
    PERMISSIONS.PRODUCTION_EDIT,

    // Mobile Features (เฉพาะ production-related)
    PERMISSIONS.MOBILE_DASHBOARD,
    PERMISSIONS.MOBILE_SCAN, // สแกน QR สำหรับการผลิต
    PERMISSIONS.MOBILE_TASKS, // งานการผลิต
    PERMISSIONS.MOBILE_PROFILE
  ],

  Operator: [
    PERMISSIONS.DASHBOARD,

    PERMISSIONS.PRODUCTION_VIEW,
    PERMISSIONS.PRODUCTION_CREATE,
    PERMISSIONS.PRODUCTION_EDIT,

    PERMISSIONS.MOLD_VIEW,
    PERMISSIONS.MOLD_CREATE,
    PERMISSIONS.MOLD_EDIT,

    PERMISSIONS.STOCK_GEM_VIEW,
    PERMISSIONS.STOCK_GEM_CREATE,
    PERMISSIONS.STOCK_GEM_EDIT,

    PERMISSIONS.CUSTOMER_VIEW,
    PERMISSIONS.CUSTOMER_CREATE,
    PERMISSIONS.CUSTOMER_EDIT,

    PERMISSIONS.REPORT_VIEW,

    PERMISSIONS.WORKER_VIEW,
    PERMISSIONS.WORKER_CREATE,
    PERMISSIONS.WORKER_EDIT,

    // Mobile Features (Operator มีสิทธิ์ส่วนใหญ่)
    PERMISSIONS.MOBILE_DASHBOARD,
    PERMISSIONS.MOBILE_SCAN,
    PERMISSIONS.MOBILE_TASKS,
    PERMISSIONS.MOBILE_PROFILE,
    PERMISSIONS.MOBILE_NOTIFICATIONS
  ],

  Sale: [
    PERMISSIONS.SALE_VIEW,
    PERMISSIONS.SALE_CREATE,

    // Mobile Features (เฉพาะพื้นฐาน)
    PERMISSIONS.MOBILE_DASHBOARD,
    PERMISSIONS.MOBILE_PROFILE
  ]
}
